---
- name: Install and configure Docker
  hosts: all
  become: yes
  tasks:
    - name: Wait for a random time to avoid apt lock
      wait_for:
        timeout: "{{ 5 + 5|random }}"

    - name: Ensure previous apt processes are terminated
      shell: |
        while fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 1; done
        while fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do sleep 1; done
        while fuser /var/lib/apt/lists/lock >/dev/null 2>&1; do sleep 1; done
        if pgrep -a apt; then
          kill -9 $(pgrep apt)
        fi
      retries: 10
      delay: 5

    - name: Ensure apt-get is not running
      shell: |
        pgrep -x apt && killall -9 apt || true
      retries: 10
      delay: 5

    - name: Clean up apt locks
      shell: |
        rm -rf /var/lib/dpkg/lock
        rm -rf /var/lib/dpkg/lock-frontend
        rm -rf /var/lib/apt/lists/lock
      ignore_errors: true

    - name: Debug apt sources list
      shell: cat /etc/apt/sources.list
      register: sources_list
    - debug:
        var: sources_list.stdout_lines

    - name: Update apt cache using shell
      shell: apt-get update
      register: update_result
      retries: 5
      delay: 15
      until: update_result.rc == 0
      ignore_errors: true

    - name: Ensure required packages are installed
      shell: |
        apt-get install -y apt-transport-https ca-certificates curl software-properties-common
      register: install_result
      retries: 5
      delay: 15
      until: install_result.rc == 0
      ignore_errors: true

    - name: Add Docker GPG key
      shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
      register: gpg_result
      retries: 5
      delay: 15
      until: gpg_result.rc == 0
      ignore_errors: true

    - name: Add Docker repository
      shell: |
        add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
      register: repo_result
      retries: 5
      delay: 15
      until: repo_result.rc == 0
      ignore_errors: true

    - name: Update apt cache after adding Docker repo
      shell: apt-get update
      register: update_docker_repo_result
      retries: 5
      delay: 15
      until: update_docker_repo_result.rc == 0
      ignore_errors: true

    - name: Install Docker
      shell: |
        apt-get install -y docker-ce
      register: docker_install_result
      retries: 5
      delay: 15
      until: docker_install_result.rc == 0
      ignore_errors: true

    - name: Ensure Docker service is started
      shell: |
        service docker start
      register: docker_service_result
      retries: 5
      delay: 15
      until: docker_service_result.rc == 0
      ignore_errors: true