version: '3.8'

services:
  ansible:
    build: .
    container_name: ansible-container
    volumes:
      - ./playbook.yaml:/playbook.yaml
    networks:
      - ansible-network

networks:
  ansible-network:
    driver: bridge