---
- hosts: all
  become: yes
  tasks:
    - name: Atualizar lista de pacotes apt
      apt:
        update_cache: yes

    - name: Instalar pacotes necessários
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

    - name: Adicionar chave GPG oficial do Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Adicionar repositório Docker
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Instalar Docker
      apt:
        name: docker-ce
        state: present

    - name: Iniciar e habilitar serviço Docker
      systemd:
        name: docker
        enabled: yes
        state: started