version: '3.8'

services:
  rundeck:
    image: intimatemerger/rundeck
    container_name: app_rundeck
    links:
      - db:db_host
    ports:
      - "4440:4440"
    environment:
      RUNDECK_URL: http://localhost:4440
      RUNDECK_MYSQL_HOST: db_host
      RUNDECK_GRAILS_URL: http://localhost:4440
      RUNDECK_SERVER_UUID: ${UUID}
      RUNDECK_PASSWORD_STORAGE_PATH: /home/rundeck/server/data/storage
      RUNDECK_ADMIN_USERNAME: myuser
      RUNDECK_ADMIN_PASSWORD: mypassword

  db:
    image: mariadb
    container_name: db_rundeck
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rundeck
      MYSQL_USER: rundeck
      MYSQL_PASSWORD: rundeck

name: minsait_rundeck

# ------

# Docker-compose que já copia as informações do job pra dentro do Rundeck

# version: '3.8'

# services:
#   rundeck:
#     image: intimatemerger/rundeck
#     container_name: app_rundeck
#     ports:
#       - "4440:4440"
#     volumes:
#       - ./rundeck_data:/home/rundeck/server/data
#     environment:
#       RUNDECK_URL: http://localhost:4440
#       RUNDECK_MYSQL_HOST: db_host
#       RUNDECK_GRAILS_URL: http://localhost:4440
#       RUNDECK_SERVER_UUID: ${UUID}
#       RUNDECK_PASSWORD_STORAGE_PATH: /home/rundeck/server/data/storage
#       RUNDECK_ADMIN_USERNAME: myuser
#       RUNDECK_ADMIN_PASSWORD: mypassword
#     entrypoint: >
#       /bin/bash -c "mkdir -p /home/rundeck/server/data/projects/myproject/etc/ && \
#       cp -r /home/rundeck/job_data/* /home/rundeck/server/data/projects/myproject/etc/ && \
#       /docker-entrypoint.sh"

#   db:
#     image: mariadb
#     container_name: db_rundeck
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: rundeck
#       MYSQL_USER: rundeck
#       MYSQL_PASSWORD: rundeck

# networks:
#   default:
#     name: minsait_rundeck_network
