version: '3.8'

services:
  rundeck:
    image: intimatemerger/rundeck
    container_name: app_rundeck
    ports:
      - "4440:4440"
    environment:
      RUNDECK_URL: http://localhost:4440
      RUNDECK_MYSQL_HOST: db
      RUNDECK_GRAILS_URL: http://localhost:4440
      RUNDECK_SERVER_UUID: ${UUID}
      RUNDECK_PASSWORD_STORAGE_PATH: /home/rundeck/server/data/storage
      RUNDECK_ADMIN_USERNAME: myuser
      RUNDECK_ADMIN_PASSWORD: mypassword
    links:
      - db:db_host
    volumes:
      - ./rundeck_data:/home/rundeck/server/data

  db:
    image: mariadb
    container_name: db_rundeck
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rundeck
      MYSQL_USER: rundeck
      MYSQL_PASSWORD: rundeck

networks:
  default:
    name: minsait_rundeck_network