name: projeto automatizado completo etapa 3 cicd deploy aplicacao

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Create terraform.tfvars
        run: |
          echo 'aws_access_key = "${{ secrets.AWS_ACCESS_KEY_ID }}"' > Terraform_IaC/terraform.tfvars
          echo 'aws_secret_key = "${{ secrets.AWS_SECRET_ACCESS_KEY }}"' >> Terraform_IaC/terraform.tfvars
          echo 'aws_region     = "us-east-1"' >> Terraform_IaC/terraform.tfvars
          echo 'ami_id         = "ami-04a81a99f5ec58529"' >> Terraform_IaC/terraform.tfvars
          echo 'instance_type  = "t2.micro"' >> Terraform_IaC/terraform.tfvars
        working-directory: Terraform_IaC

      - name: Terraform Init
        run: terraform init
        working-directory: Terraform_IaC

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: Terraform_IaC

      - name: Clean up
        run: rm Terraform_IaC/terraform.tfvars